---
apiVersion: v1
kind: Pod
metadata:
  name: semgrep
  labels:
    app: web
spec:
  containers:
    - name: semgrep
      image: returntocorp/semgrep
      command: ["/bin/sh"]
      args:
        - "-c"
        - >
          mkdir /tmp/repo && cd /tmp/repo &&
          echo "Checking out $SEMGREP_REPO_NAME" && 
          HOME=/secrets git clone --depth=1 $SEMGREP_REPO_URL . && 
          semgrep ci 
          --timeout 3 --interfile-timeout 180 
          --disable-version-check --metrics=off --no-suppress-errors
          --verbose ||
          true
      env:
        - name: SEMGREP_REPO_NAME
          value: chsarp-basic-example
        - name: SEMGREP_REPO_URL
          value: https://gitlab.com/r2c-cse/chsarp-basic-example.git
        - name: SEMGREP_BRANCH
          value: main
        - name: SEMGREP_APP_TOKEN
          value: 'xxxx'                                                                                                                            
